name: vite_spa

services:

  frontend:
    build:
      context: .
    # command: yarn dev
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
    ports:
      - 4000:4000
volumes:
  node_modules:
